#ifndef Strela_Ast_nodes_h
#define Strela_Ast_nodes_h

#include "ArrayTypeExpr.h"
#include "AssignExpr.h"
#include "BinopExpr.h"
#include "BlockStmt.h"
#include "CallExpr.h"
#include "EnumElement.h"
#include "Expr.h"
#include "ExprStmt.h"
#include "FieldDecl.h"
#include "FuncDecl.h"
#include "IdExpr.h"
#include "IdTypeExpr.h"
#include "IfStmt.h"
#include "ImportStmt.h"
#include "LitExpr.h"
#include "NewExpr.h"
#include "Node.h"
#include "Param.h"
#include "PostfixExpr.h"
#include "RetStmt.h"
#include "ScopeExpr.h"
#include "Stmt.h"
#include "TypeDecl.h"
#include "TypeExpr.h"
#include "UnaryExpr.h"
#include "VarDecl.h"
#include "WhileStmt.h"
#include "InterfaceDecl.h"
#include "InterfaceMethodDecl.h"

// types
#include "ArrayType.h"
#include "ClassDecl.h"
#include "EnumDecl.h"
#include "FloatType.h"
#include "FuncType.h"
#include "IntType.h"
#include "ModDecl.h"
#include "NullType.h"
#include "VoidType.h"
#include "BoolType.h"
#include "TypeType.h"
#include "InvalidType.h"
#include "OverloadedFuncType.h"


#endif