// Copyright (c) 2018 Stephan Unverwerth
// This code is licensed under MIT license (See LICENSE for details)

#ifndef Strela_Ast_nodes_h
#define Strela_Ast_nodes_h

#include "ArrayLitExpr.h"
#include "ArrayTypeExpr.h"
#include "AssignExpr.h"
#include "BinopExpr.h"
#include "BlockStmt.h"
#include "CallExpr.h"
#include "CastExpr.h"
#include "EnumElement.h"
#include "Expr.h"
#include "ExprStmt.h"
#include "FieldDecl.h"
#include "FuncDecl.h"
#include "GenericParam.h"
#include "GenericReificationExpr.h"
#include "IdExpr.h"
#include "IfStmt.h"
#include "ImportStmt.h"
#include "InterfaceDecl.h"
#include "InterfaceMethodDecl.h"
#include "InterfaceFieldDecl.h"
#include "IsExpr.h"
#include "LitExpr.h"
#include "MapLitExpr.h"
#include "NewExpr.h"
#include "Node.h"
#include "NullableTypeExpr.h"
#include "Param.h"
#include "PostfixExpr.h"
#include "RetStmt.h"
#include "ScopeExpr.h"
#include "Stmt.h"
#include "SubscriptExpr.h"
#include "ThisExpr.h"
#include "TypeAliasDecl.h"
#include "TypeDecl.h"
#include "UnaryExpr.h"
#include "UnionTypeExpr.h"
#include "VarDecl.h"
#include "WhileStmt.h"

// types
#include "ArrayType.h"
#include "BoolType.h"
#include "ClassDecl.h"
#include "EnumDecl.h"
#include "FloatType.h"
#include "FuncType.h"
#include "IntType.h"
#include "InvalidType.h"
#include "ModDecl.h"
#include "NullType.h"
#include "OverloadedFuncType.h"
#include "PointerType.h"
#include "TypeType.h"
#include "UnionType.h"
#include "VoidType.h"


#endif