#ifndef Strela_Ast_nodes_h
#define Strela_Ast_nodes_h

#include "AstNode.h"
#include "AstModDecl.h"
#include "AstFuncDecl.h"
#include "AstParam.h"
#include "AstVarDecl.h"
#include "AstClassDecl.h"
#include "AstStmt.h"
#include "AstRetStmt.h"
#include "AstExprStmt.h"
#include "AstAssignExpr.h"
#include "AstExpr.h"
#include "AstScopeExpr.h"
#include "AstLitExpr.h"
#include "AstIdExpr.h"
#include "AstCallExpr.h"
#include "AstBinopExpr.h"
#include "AstBlockStmt.h"
#include "AstIfStmt.h"
#include "AstFieldDecl.h"
#include "AstNewExpr.h"
#include "AstTypeExpr.h"
#include "AstIdTypeExpr.h"
#include "AstWhileStmt.h"
#include "AstPostfixExpr.h"
#include "AstUnaryExpr.h"
#include "AstArrayTypeExpr.h"
#include "AstImportStmt.h"
#include "AstEnumDecl.h"
#include "AstEnumElement.h"

#endif